# Generated by Django 4.0 on 2022-01-17 16:24

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    Role.objects.bulk_create([
        Role(id=1, user_role='SUPER_ADMIN'),
        Role(id=2, user_role='ADMIN'),
        Role(id=3, user_role='CLIENT'),
        Role(id=4, user_role='INFLUENCER'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
