# Generated by Django 4.0.2 on 2022-03-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandcategory',
            old_name='category_name',
            new_name='brand_category',
        ),
    ]
