# Generated by Django 4.0.2 on 2022-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_adminsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndetail',
            name='campaign_title',
            field=models.CharField(default='campaign_title', max_length=300),
            preserve_default=False,
        ),
    ]
