# Generated by Django 4.0.2 on 2022-07-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_campaigndetail_campaign_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branddetail',
            name='category',
        ),
        migrations.DeleteModel(
            name='BrandCategory',
        ),
    ]
