# Generated by Django 4.0.2 on 2022-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_remove_branddetail_category_delete_brandcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndetail',
            name='total_campaigns',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='total_influencers',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndetail',
            name='campaign_total_days',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
