# Generated by Django 4.0.2 on 2022-07-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_campaigndetail_total_campaigns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndates',
            name='day_count',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
