# Generated by Django 4.0.2 on 2022-07-02 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_campaigndates_day_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndetail',
            name='is_active',
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='campaign_completed_days',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='campaign_cycle_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='campaign_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='campaign_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='campaign_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Completed')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
