# Generated by Django 4.0.2 on 2022-02-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfluencerCategories',
        ),
    ]
