# Generated by Django 4.0.2 on 2022-03-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_delete_influencercategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerschildren',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
