# Generated by Django 4.0.2 on 2022-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_alter_influencerschildren_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencersCategories',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('influencer_category', models.CharField(max_length=50)),
            ],
        ),
    ]
